# Generated by Django 5.0.6 on 2024-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicoapp', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=15)),
                ('doctor', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
